apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - managed-certificate.yaml
  - secret.yaml
  - service.yaml

images:
  - name: ghcr.io/stevelin100132/steve-test-app
    newTag: ${APP_VERSION}