apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: steve-test-app-api-gsm
spec:
  provider: gcp
  parameters:
    secrets:
      - resourceName: "projects/464650102550/secrets/APP_ID"
        version: "latest"
        path: "APP_ID"