name: Deploy to GKE

on:
  push:
    branches:
      - deploy

env:
  GITHUB_ACTOR: ${{ github.actor }}
  APP_VERSION: ${{ vars.APP_VERSION }}
  GKE_ZONE: ${{ vars.GKE_ZONE }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  IMAGE_REPO: ${GITHUB_ACTOR,,}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials  ${{ secrets.GKE_CLUSTER }} --zone $GKE_ZONE --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Who am I
        run: gcloud auth list

      - name: Apply k8s manifests
        run: |
          kubectl apply -k ./k8s