name: CI - main

on:
  push:
    branches:
      - 'master'

jobs:
  unit-test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true # 一個 job fail，其他 job 會被取消
      matrix:
        node-version: [14, 16, 18, 20, 22]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test
      
      - name: Send Slack notification on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": ":x: Unit tests failed in `${{ github.repository }}` on branch `${{ github.ref_name }}` by `${{ github.actor }}`.\nCheck run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

  build-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: unit-test # 等 unit-test 成功才執行

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Set image tag
        id: tag
        run: echo "TAG=${{ vars.APP_VERSION }}" >> $GITHUB_ENV

      - name: Lowercase github.actor
        run: echo "LOWER_ACTOR=${GITHUB_ACTOR,,}" >> $GITHUB_ENV
        env:
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/$LOWER_ACTOR/${{ vars.IMAGE_NAME }}:${{ env.TAG }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/$LOWER_ACTOR/${{ vars.IMAGE_NAME }}:${{ env.TAG }}